import { Kanit } from "next/font/google";
import { NavbarComponents } from "./components/Navbar";
import SessionWrapper from "./sessionlayout";
import "./globals.css";
const kanit = Kanit({ weight: ["400"], subsets: ["thai"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={kanit.className}>
          <NavbarComponents />{children}
        </body>
      </html>
    </SessionWrapper>
  );
}